#!/bin/sh
#
# Copyright (c) 2014, 2020, The Linux Foundation. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#


. /lib/uboot-envtools.sh
. /lib/functions.sh
. /usr/share/libubox/jshn.sh

get_board_details() {
        local JSON_FILE="/etc/board.json"
        local info_value

        json_load_file "$JSON_FILE"

        case $1 in
                "model_name")
                        json_select model
                        json_get_var info_value name
                        info_value=${info_value##*/}
                        ;;
                *)
                        json_get_var info_value $1
                        ;;
        esac

        echo $info_value
}

ubootenv_mtdinfo () {
	UBOOTENV_PART=$(cat /proc/mtd | grep APPSBLENV)
	mtd_dev=$(echo $UBOOTENV_PART | awk '{print $1}' | sed 's/:$//')
	mtd_size=$(echo $UBOOTENV_PART | awk '{print "0x"$2}')
	mtd_erase=$(echo $UBOOTENV_PART | awk '{print "0x"$3}')
	nor_flash=$(find /sys/bus/spi/devices/*/mtd -name ${mtd_dev})

	if [ -z "$UBOOTENV_PART" ]; then
		mtd_dev=$(echo $(find_mmc_part "0:APPSBLENV") | sed 's/^.\{5\}//')
		if [ -n "$mtd_dev" ]; then
			EMMC_UBOOTENV_PART=$(cat /proc/partitions | grep $mtd_dev)
			#convert block to bytes
			emmc_ubootenv_size=`expr $(echo $EMMC_UBOOTENV_PART | awk '{print $3}') \* 1024`
			ubootenv_size=0x`printf "%x" $emmc_ubootenv_size`
		fi
		mtd_erase=""
	elif [ -n "$nor_flash" ]; then
		ubootenv_size=$mtd_size
		sectors=$(( $ubootenv_size / $mtd_erase ))
		sectors=0x`printf "%x" $sectors`
	else
		# size is fixed to 0x40000 in u-boot
		ubootenv_size=0x40000
		sectors=$(( $ubootenv_size / $mtd_erase ))
		sectors=0x`printf "%x" $sectors`
	fi

	echo /dev/$mtd_dev 0x0 $ubootenv_size $mtd_erase $sectors
}

validate_device_node() {
	config_get dev $1 dev
	if [ "$dev" != "$2" ] || [ ! -e /etc/fw_env.config ]; then
		rm /etc/config/ubootenv /etc/fw_env.config
		return;
	fi

	exit 0
}

[ -e /etc/config/ubootenv ] && {
	config_load ubootenv
	config_foreach validate_device_node ubootenv $(default_uboot_env)
}

echo "" > /etc/config/ubootenv

envset=$(get_board_details "uboot-envtool")

case "$envset" in
	true)
		ubootenv_add_uci_config $(ubootenv_mtdinfo)
		;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
