
filter f_kfence_start {
 program("kernel") and match("BUG: KFENCE:" value("MESSAGE"));
};

destination d_console {
 program("/usr/sbin/kfence-handler.sh" template("HOST=${HOST} MSG=${MESSAGE}\n")
         keep-alive(yes)
         flush-lines(1));
};

log {
 source(kernel);
 filter(f_kfence_start);
 destination(d_console);
};
